name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14

      - name: Configure CMake (Threaded Wasm)
        run: emcmake cmake -G Ninja -B build-box3d-wasm -DCMAKE_BUILD_TYPE=Release -DBOX3D_SAMPLES=OFF -DBOX3D_UNIT_TESTS=OFF -DBOX3D_VALIDATE=OFF -DBUILD_SHARED_LIBS=OFF -DBOX3D_WASM_MODULE=ON -DBOX3D_EMSCRIPTEN_PTHREADS=ON

      - name: Build Threaded Wasm Target
        run: cmake --build build-box3d-wasm --config Release

      - name: Configure CMake (Single-Thread Wasm)
        run: emcmake cmake -G Ninja -B build-box3d-wasm-single -DCMAKE_BUILD_TYPE=Release -DBOX3D_SAMPLES=OFF -DBOX3D_UNIT_TESTS=OFF -DBOX3D_VALIDATE=OFF -DBUILD_SHARED_LIBS=OFF -DBOX3D_WASM_MODULE=ON -DBOX3D_EMSCRIPTEN_PTHREADS=OFF

      - name: Build Single-Thread Wasm Target
        run: cmake --build build-box3d-wasm-single --config Release

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Sync WASM artifacts to Web
        run: |
          npm run wasm:sync
          npm run wasm:sync:threaded

      - name: Build Web App
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
